### ISSUE TITLE
Forward incoming SMS from each dongle to different email addresses

### ISSUE THREAD

**Issue by kalhori124** [garronej/chan-dongle-extended-pages#1]
Hi,

I have two dongles and incoming SMS from both dongles are forwarded to one email address and everything is fine.
How can I forward SMS from each dongle to different email address?

Is it possible to have individual setting for each dongle in extensions_custom.conf for email forwarding?

Regards,

**Comment by garronej** [comment]
Hi @kalhori124,  
This sound like something out of the scope of chan_dongle_extended.  

Sorry I can't help,  

Best regards
