### ISSUE TITLE
Script does not work on Ubuntu 22.04

### ISSUE THREAD

**Issue by controloye** [garronej/chan-dongle-extended-pages#6]
I believe python is now python3 on Ubuntu 22.04

anyway following is output

$ -> node dist/bin/installer.js install
---Installing chan_dongle---
Looking for git ... git executable found. OK
Installing or upgrading python package...Command failed: apt-get -y install python
E: Package 'python' has no installation candidate

An error occurred: 'Command failed: apt-get -y install python
E: Package 'python' has no installation candidate

root@dev:/usr/share/dongle#

**Comment by geosohaib** [comment]
create soft link to python3

ln -sf /usr/bin/python3 /usr/bin/python

**Comment by garronej** [comment]
Chan-dongle-extended work with `pyhton` 2. Before installing you must have `python` installed and il must be in v2.X
