### ISSUE TITLE
Dongle's order is changed on service restart

### ISSUE THREAD

**Issue by geosohaib** [garronej/chan-dongle-extended-pages#7]
to manage dongles balance and other statistics dongle order and position is very important

But on every reboot, service restart or on dongle replug order and position of dongles is changed 

Is there anyway to keep them in order and not allow to change position such as bind by IMEI etc.

**Comment by garronej** [comment]
Sorry I wrote an answer but I forgot to send it.  

No it's not currently possible.  
The friendly name is assigned randomly depending of what dongle it sees first.  

Why dont you use the IMEI (dongle) or IMSI (sim) as ID?

**Comment by geosohaib** [comment]
Thank you for your prompt reply.

I tried to use IMEI but after the restart of chan_dongle service the file dongle.conf is rewritten.

**Comment by garronej** [comment]
But I mean in your code, (dialplan I assume ?) 
Why don't you use the IMEI to select the dongle you want to interact with.  
Why do you need to use the friendly name?
